spring:
  application:
    name: spring-book-management
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//dbsrvoractib0:1521/oractib0
    username: EDU1D001ONTW
    password: EDU1D001ONTW
